import type { Metadata } from "next";
import "./globals.css";

import StaggeredMenu from '../components/StaggeredMenu';

const menuItems = [
  { label: 'Home', ariaLabel: 'Go to home page', link: '/' },
  { label: 'Project', ariaLabel: 'Browse my projects', link: '/projects'},
  { label: 'Contact', ariaLabel: 'Get in touch', link: '/contact' }
];

const socialItems = [
  { label: 'GitHub', link: 'https://github.com/rayyansur' },
  { label: 'LinkedIn', link: 'https://linkedin.com/in/rayyan-surani' }
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <div style={{height: '100vh', width: '0vh', background: '#1a1a1a'}} className={"fixed inset-0 z-10 bg-black"}>
      <StaggeredMenu
          position="right"
          items={menuItems}
          socialItems={socialItems}
          displaySocials={true}
          displayItemNumbering={true}
          menuButtonColor="#fff"
          openMenuButtonColor="#000"
          changeMenuColorOnOpen={true}
          colors={['#0f5cff', '#6554fc']}
          isFixed={true}
          accentColor="#6554fc"
      />
    </div>
    {children}

    </body>

    </html>
  );
}
